name: Generate Snake Animation ğŸ

on:
  schedule:
    - cron: "0 0 * * *" # roda todos os dias
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositÃ³rio
        uses: actions/checkout@v3

      - name: Gerar animaÃ§Ã£o da cobra
        uses: Platane/snk@v3
        with:
          github_user_name: CaioEnzo23
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e push dos SVGs
        uses: EndBug/add-and-commit@v9
        with:
          message: "AtualizaÃ§Ã£o da animaÃ§Ã£o Snake ğŸ"
          add: "dist/*.svg"
